/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VesserathRouteImport } from './routes/vesserath'
import { Route as TheWifeOfWarRouteImport } from './routes/the-wife-of-war'
import { Route as TheBoneTrialsRouteImport } from './routes/the-bone-trials'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const VesserathRoute = VesserathRouteImport.update({
  id: '/vesserath',
  path: '/vesserath',
  getParentRoute: () => rootRouteImport,
} as any)
const TheWifeOfWarRoute = TheWifeOfWarRouteImport.update({
  id: '/the-wife-of-war',
  path: '/the-wife-of-war',
  getParentRoute: () => rootRouteImport,
} as any)
const TheBoneTrialsRoute = TheBoneTrialsRouteImport.update({
  id: '/the-bone-trials',
  path: '/the-bone-trials',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/the-bone-trials': typeof TheBoneTrialsRoute
  '/the-wife-of-war': typeof TheWifeOfWarRoute
  '/vesserath': typeof VesserathRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/the-bone-trials': typeof TheBoneTrialsRoute
  '/the-wife-of-war': typeof TheWifeOfWarRoute
  '/vesserath': typeof VesserathRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/the-bone-trials': typeof TheBoneTrialsRoute
  '/the-wife-of-war': typeof TheWifeOfWarRoute
  '/vesserath': typeof VesserathRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/the-bone-trials'
    | '/the-wife-of-war'
    | '/vesserath'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/the-bone-trials'
    | '/the-wife-of-war'
    | '/vesserath'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/the-bone-trials'
    | '/the-wife-of-war'
    | '/vesserath'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TheBoneTrialsRoute: typeof TheBoneTrialsRoute
  TheWifeOfWarRoute: typeof TheWifeOfWarRoute
  VesserathRoute: typeof VesserathRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vesserath': {
      id: '/vesserath'
      path: '/vesserath'
      fullPath: '/vesserath'
      preLoaderRoute: typeof VesserathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-wife-of-war': {
      id: '/the-wife-of-war'
      path: '/the-wife-of-war'
      fullPath: '/the-wife-of-war'
      preLoaderRoute: typeof TheWifeOfWarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-bone-trials': {
      id: '/the-bone-trials'
      path: '/the-bone-trials'
      fullPath: '/the-bone-trials'
      preLoaderRoute: typeof TheBoneTrialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TheBoneTrialsRoute: TheBoneTrialsRoute,
  TheWifeOfWarRoute: TheWifeOfWarRoute,
  VesserathRoute: VesserathRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
